export enum WorkerActions {
  "SET_PUMP_STATE" = "SET_PUMP_STATE",
  "SET_VALVE_STATE" = "SET_VALVE_STATE",
  "SET_PTU_STATE" = "SET_PTU_STATE",
  "UPDATE_SETTINGS" = "UPDATE_SETTINGS",
  "RESET_SIMULATION" = "RESET_SIMULATION",
}
